export const suraList = [
  'Adobo',
  'Adobong Pusit',
  'Adobong Talong',
  'Bangus Prito',
  'Beef Mechado',
  'Beef Tapa',
  'Beef with Broccoli',
  'Bistek Tagalog',
  'Bulalo',
  'Champorado',
  'Chicken Adobo',
  'Chicken Inasal',
  'Chopseuy',
  'Chowking',
  'Crispy Tortang Alamang',
  'Dalo-dalo',
  'Dinuguan',
  'Easy Chicken Chop Suey',
  'Fried Chicken',
  'Ginataang Kalabasa',
  'Ginataang Tulingan',
  'Giniling Beef',
  'Giniling Pork',
  'Giniling Sagmaw',
  'Guisadong Ampalaya',
  'Igado',
  'Jollibee',
  'Kanto Fried Chicken',
  'Kare-Kare',
  'KFC',
  'Laing',
  'Lechon Baboy',
  'Lechon Kawali',
  'Lechon Paksiw',
  'Lichon Manok',
  'Logaw',
  'Mang Inasal',
  'Nilagang Baka',
  'Paksiw na Isda',
  'Pinakbet',
  'Pinoy Ulam',
  'Pork Adobo',
  'Pork and Beans Gata',
  'Pork Menudo',
  'Pork Sinigang',
  'Pork Sisig',
  'Sinigang na Baboy',
  'Seseg',
  'Shipaghetti',
  'Sinigang-erms',
  'Sopas',
  'Sweet and Sour Fish Fillets',
  'Tapa',
  'Tenola',
  'Tinolang Manok',
  'Tokwa’t Baboy',
  'Ginataang Kalabasa',
  'Pinakbet',
  'Adobong Talong',
  'Guisadong Ampalaya',
  'Laing',
];
